//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los cambios en este archivo pueden causar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReparaciones
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Literal litSaludo;
        protected global::System.Web.UI.WebControls.Literal litEquipos;
        protected global::System.Web.UI.WebControls.Literal litUsuarios;
        protected global::System.Web.UI.WebControls.Literal litTecnicos;
        protected global::System.Web.UI.WebControls.Literal litAbiertas;
        protected global::System.Web.UI.WebControls.GridView gvUltimas;
    }
}
