//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los cambios en este archivo pueden causar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReparaciones
{
    public partial class Detalles
    {
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;
        protected global::System.Web.UI.WebControls.HiddenField hdnDetalleID;
        protected global::System.Web.UI.WebControls.DropDownList ddlReparacion;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.TextBox txtInicio;
        protected global::System.Web.UI.WebControls.TextBox txtFin;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.GridView gvDetalles;
    }
}
