//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los cambios en este archivo pueden causar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReparaciones
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtUsuario;
        protected global::System.Web.UI.WebControls.TextBox txtContrasena;
        protected global::System.Web.UI.WebControls.Button btnEntrar;
    }
}
