//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los cambios en este archivo pueden causar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReparaciones
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litUsuario;
        protected global::System.Web.UI.WebControls.LinkButton btnSalir;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navInicio;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navEquipos;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navUsuarios;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navTecnicos;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navReparaciones;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navDetalles;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navAsignaciones;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder Contenido;
    }
}
