//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los cambios en este archivo pueden causar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReparaciones
{
    public partial class Tecnicos
    {
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;
        protected global::System.Web.UI.WebControls.HiddenField hdnTecnicoID;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtEspecialidad;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.GridView gvTecnicos;
    }
}
